### PR TITLE
Update installer script

### PR DESCRIPTION
**Pull request by bovirus**
@URUWorks 

Fix some issues about exe file properties and installer improvements

- Add italian language ins election
- Add in [Setup] several improvemnt about FileVesrion/Copyright author, etc.

Pelase define if you are using Inno Setup 5.x or 6.x. If you are using Inno Setup 6.x could be possible to automatize value of app version. If you add Copyurith year in Copyright info pelase report the starting year for your copyright (the end year is current year).

Thanks.

### CODE REVIEW

**Comment by URUWorks** [comment]
Yes, Inno Setup 6.2.2.

**Comment by bovirus** [comment]
@URUWorks 

It's possible with IS 6.x to create a function to read version from app exe fiule (ex 1.0.1.5) and set two variables: one with"." (ex. 1.0.1.5) and one without "." (ex. 1015).

What's about starting year for copyright your program?

**Comment by URUWorks** [comment]
> t's possible with IS 6.x to create a function to read version from app exe fiule (ex 1.0.1.5) and set two variables: one with"." (ex. 1.0.1.5) and one without "." (ex. 1015).

Can you incorporate it?


> What's about starting year for copyright your program?

Do you mean LegalCopyright? Currently it is:
Copyright © 2023-2024 URUWorks.

**Comment by bovirus** [comment]
@URUWorks 

"Copyright" and "©" are synonyms.
I believe that could be
"Copyright 2023-xxxx URUWorks" or "© 2023-xxxx URUWorks".
What's do you like better?

**Comment by URUWorks** [comment]
Maybe "Copyright 2023-xxxx URUWorks"

**Comment by bovirus** [comment]
@URUWorks 

Please check what I added.
Copyright is already Field name.
then in the File properties with your propsoal will be

Copyright:  "Copyright 2023-xxxx URUWorks"

For me is better

Copyright:  "2023-xxxx URUWorks"

then the text could be "2023-xxxx URUWorks"

**Comment by URUWorks** [comment]
I understand, you may be right, but in most programs I have seen that they use "Copyright © 2023-xxxx xxxx".

**Comment by bovirus** [comment]
@URUWorks 

I understood.
Most of the developer that do thatseems that  didn't check and didn't know where the string is applied,
And I'm so sorry that when I explain that the typical answer is "Other use in this way".
For me is a neverending story.

I believe that it'0s betetr for you to decide not considering what other do but what do you like and for you it's better.

For me it's clear and simple use "2023-xxxx URUWorks" (final risult in exe poperties is "Copyright: 2023-xxxx URUWorks"

**Comment by URUWorks** [comment]
You're right, I change it to Copyright: "2023-xxxx URUWorks"

**Pull request merged**
