### PR TITLE
Update Installer script

### PR DESCRIPTION
**Pull request by bovirus**
@URUWorks 

Small improvement.
Get info for version for main app exe file from previous variables set (no harcioded exe file path).

### CODE REVIEW

**Comment by URUWorks** [comment]
Hello, I was testing the installer script, and I see that there is a failure,
I think the line:

`#define ShortAppVersion VersionMajor + VersionMinor + VersionRevision + VersionBuild`

should be:

`#define ShortAppVersion VersionMajor + "." + VersionMinor + "." + VersionRevision + "." + VersionBuild`

Otherwise I add all the values.

**Comment by bovirus** [comment]
@URUWorks 

If "ShortAppVersion" should be "1.2.3.4" your change is right.
If "ShortAppVersion" should be "1234" current instruction in the script is ok.

**Comment by URUWorks** [comment]
correct but current instruction in case of version “1.0.1.6” returns 8
then the generated file is ts8_win64.exe instead of ts1016.exe

**Comment by bovirus** [comment]
@URUWorks 

Correct. The fix is

#define ShortAppVersion str(VersionMajor) + str(VersionMinor) + str(VersionRevision) + str(VersionBuild)

**Comment by URUWorks** [comment]
Nice

**Pull request merged**
